<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="jadx.tests.integration.trycatch.TestTryCatch3" tests="2" skipped="0" failures="0" errors="0" timestamp="2016-04-22T15:41:02" hostname="box723" time="0.177">
  <properties/>
  <testcase name="test" classname="jadx.tests.integration.trycatch.TestTryCatch3" time="0.086"/>
  <testcase name="test2" classname="jadx.tests.integration.trycatch.TestTryCatch3" time="0.09"/>
  <system-out><![CDATA[15:41:02 INFO  - converting to dex: jadx-tmp-850067106157729940184930450977668.jar ...
15:41:02 INFO  - loading ...
15:41:02 DEBUG - Load: /tmp/jadx-tmp-850067106157729940184930450977668.jar
15:41:02 DEBUG - '.arsc' file not found
15:41:02 WARN  - Unknown 'R' class, create references to 'R'
-----------------------------------------------------------
package jadx.tests.integration.trycatch;

import org.junit.Assert;

public class TestTryCatch3$TestCls {
    private int f = 0;

    private boolean test(Object obj) {
        boolean res;
        try {
            res = exc(obj);
        } catch (Exception e) {
            res = false;
        } finally {
            this.f++;
        }
        return res;
    }

    private boolean exc(Object obj) throws Exception {
        if (!"r".equals(obj)) {
            return true;
        }
        throw new AssertionError();
    }

    public void check() {
        this.f = 0;
        Assert.assertTrue(test(null));
        Assert.assertEquals(1, (long) this.f);
        this.f = 0;
        try {
            test("r");
        } catch (AssertionError e) {
        }
        Assert.assertEquals(1, (long) this.f);
    }
}
-----------------------------------------------------------
Compilation: PASSED
Auto check: PASSED
15:41:02 INFO  - converting to dex: jadx-tmp-469246238936886928284930564003126.jar ...
15:41:02 INFO  - loading ...
15:41:02 DEBUG - Load: /tmp/jadx-tmp-469246238936886928284930564003126.jar
15:41:02 DEBUG - '.arsc' file not found
15:41:02 WARN  - Unknown 'R' class, create references to 'R'
-----------------------------------------------------------
package jadx.tests.integration.trycatch;

import org.junit.Assert;

public class TestTryCatch3$TestCls {
    private int f = 0;

    private boolean exc(Object obj) throws Exception {
        if (!"r".equals(obj)) {
            return true;
        }
        throw new AssertionError();
    }

    private boolean test(Object obj) {
        boolean exc;
        try {
            exc = exc(obj);
        } catch (Exception e) {
            exc = false;
        } finally {
            this.f++;
        }
        return exc;
    }

    public void check() {
        this.f = 0;
        Assert.assertTrue(test(null));
        Assert.assertEquals(1, (long) this.f);
        this.f = 0;
        try {
            test("r");
        } catch (AssertionError e) {
        }
        Assert.assertEquals(1, (long) this.f);
    }
}
-----------------------------------------------------------
Compilation: PASSED
Auto check: PASSED
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
